// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/api.proto

package camping

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetAllSitesRequest is currently empty
type GetAllSitesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllSitesRequest) Reset()         { *m = GetAllSitesRequest{} }
func (m *GetAllSitesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllSitesRequest) ProtoMessage()    {}
func (*GetAllSitesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{0}
}

func (m *GetAllSitesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllSitesRequest.Unmarshal(m, b)
}
func (m *GetAllSitesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllSitesRequest.Marshal(b, m, deterministic)
}
func (m *GetAllSitesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllSitesRequest.Merge(m, src)
}
func (m *GetAllSitesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllSitesRequest.Size(m)
}
func (m *GetAllSitesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllSitesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllSitesRequest proto.InternalMessageInfo

type Site struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude             float32  `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	NationalForestId     int32    `protobuf:"varint,4,opt,name=national_forest_id,json=nationalForestId,proto3" json:"national_forest_id,omitempty"`
	DistrictId           int32    `protobuf:"varint,5,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	Altitude             int32    `protobuf:"varint,6,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Notes                string   `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Site) Reset()         { *m = Site{} }
func (m *Site) String() string { return proto.CompactTextString(m) }
func (*Site) ProtoMessage()    {}
func (*Site) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{1}
}

func (m *Site) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Site.Unmarshal(m, b)
}
func (m *Site) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Site.Marshal(b, m, deterministic)
}
func (m *Site) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Site.Merge(m, src)
}
func (m *Site) XXX_Size() int {
	return xxx_messageInfo_Site.Size(m)
}
func (m *Site) XXX_DiscardUnknown() {
	xxx_messageInfo_Site.DiscardUnknown(m)
}

var xxx_messageInfo_Site proto.InternalMessageInfo

func (m *Site) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Site) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Site) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Site) GetNationalForestId() int32 {
	if m != nil {
		return m.NationalForestId
	}
	return 0
}

func (m *Site) GetDistrictId() int32 {
	if m != nil {
		return m.DistrictId
	}
	return 0
}

func (m *Site) GetAltitude() int32 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *Site) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

// GetAllSitesResponse contains information regarding a camp site
type GetAllSitesResponse struct {
	Sites                []*Site  `protobuf:"bytes,1,rep,name=sites,proto3" json:"sites,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllSitesResponse) Reset()         { *m = GetAllSitesResponse{} }
func (m *GetAllSitesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllSitesResponse) ProtoMessage()    {}
func (*GetAllSitesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{2}
}

func (m *GetAllSitesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllSitesResponse.Unmarshal(m, b)
}
func (m *GetAllSitesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllSitesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllSitesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllSitesResponse.Merge(m, src)
}
func (m *GetAllSitesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllSitesResponse.Size(m)
}
func (m *GetAllSitesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllSitesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllSitesResponse proto.InternalMessageInfo

func (m *GetAllSitesResponse) GetSites() []*Site {
	if m != nil {
		return m.Sites
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAllSitesRequest)(nil), "camping.GetAllSitesRequest")
	proto.RegisterType((*Site)(nil), "camping.Site")
	proto.RegisterType((*GetAllSitesResponse)(nil), "camping.GetAllSitesResponse")
}

func init() { proto.RegisterFile("api/proto/api.proto", fileDescriptor_2df576b66d12087a) }

var fileDescriptor_2df576b66d12087a = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0xe5, 0xb4, 0x69, 0xff, 0x4e, 0xf5, 0x57, 0x30, 0xed, 0x22, 0x94, 0x4a, 0x44, 0x61,
	0x93, 0x05, 0x6a, 0x44, 0xd9, 0xb1, 0x43, 0x48, 0xa0, 0x6e, 0xd3, 0x03, 0x54, 0x26, 0x31, 0xd1,
	0x48, 0xc6, 0x0e, 0xb1, 0xdb, 0x03, 0x70, 0x05, 0x4e, 0x86, 0xb8, 0x02, 0x07, 0x41, 0xb1, 0xdb,
	0x02, 0x82, 0x5d, 0xde, 0xfb, 0x5e, 0x3c, 0xcf, 0x63, 0x18, 0xf3, 0x9a, 0xb2, 0xba, 0xd1, 0x56,
	0x67, 0xbc, 0xa6, 0xb9, 0xfb, 0xc2, 0x7e, 0xc1, 0x9f, 0x6a, 0x52, 0xd5, 0x74, 0x56, 0x69, 0x5d,
	0x49, 0xd1, 0xa2, 0x8c, 0x2b, 0xa5, 0x2d, 0xb7, 0xa4, 0x95, 0xf1, 0xb1, 0x64, 0x02, 0x78, 0x2f,
	0xec, 0x8d, 0x94, 0x2b, 0xb2, 0xc2, 0xe4, 0xe2, 0x79, 0x23, 0x8c, 0x4d, 0xde, 0x18, 0x74, 0x5b,
	0x03, 0x47, 0x10, 0x50, 0x19, 0xb1, 0x98, 0xa5, 0x9d, 0x3c, 0xa0, 0x12, 0xa7, 0xf0, 0x4f, 0x72,
	0x4b, 0x76, 0x53, 0x8a, 0x28, 0x88, 0x59, 0x1a, 0xe4, 0x07, 0x8d, 0x33, 0x18, 0x48, 0xad, 0x2a,
	0x0f, 0x3b, 0x0e, 0x7e, 0x19, 0x78, 0x01, 0xa8, 0xdc, 0x64, 0x2e, 0xd7, 0x8f, 0xba, 0x11, 0xc6,
	0xae, 0xa9, 0x8c, 0xba, 0x31, 0x4b, 0xc3, 0xfc, 0x68, 0x4f, 0xee, 0x1c, 0x58, 0x96, 0x78, 0x06,
	0xc3, 0x92, 0x8c, 0x6d, 0xa8, 0x70, 0xb1, 0xd0, 0xc5, 0x60, 0x6f, 0x2d, 0x5d, 0x11, 0x2e, 0x77,
	0x45, 0x7a, 0x8e, 0x1e, 0x34, 0x4e, 0x20, 0x54, 0xda, 0x0a, 0x13, 0xf5, 0x63, 0x96, 0x0e, 0x72,
	0x2f, 0x92, 0x6b, 0x18, 0xff, 0xb8, 0xa9, 0xa9, 0xb5, 0x32, 0x02, 0xcf, 0x21, 0x34, 0xad, 0x11,
	0xb1, 0xb8, 0x93, 0x0e, 0x17, 0xff, 0xe7, 0xbb, 0xbd, 0xcd, 0xdb, 0x58, 0xee, 0xd9, 0x62, 0x03,
	0xa3, 0x5b, 0x6f, 0xaf, 0x44, 0xb3, 0xa5, 0x42, 0x60, 0x01, 0xc3, 0x6f, 0xa7, 0xe1, 0xe9, 0xe1,
	0xb7, 0xdf, 0xdb, 0x9c, 0xce, 0xfe, 0x86, 0xbe, 0x40, 0x72, 0xf2, 0xf2, 0xfe, 0xf1, 0x1a, 0x8c,
	0xf1, 0x38, 0xdb, 0x5e, 0x66, 0xbb, 0x60, 0xe6, 0xc6, 0x3e, 0xf4, 0xdc, 0x1b, 0x5d, 0x7d, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x07, 0xe3, 0xa8, 0x61, 0xe1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CampingServiceClient is the client API for CampingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CampingServiceClient interface {
	GetAllSites(ctx context.Context, in *GetAllSitesRequest, opts ...grpc.CallOption) (*GetAllSitesResponse, error)
}

type campingServiceClient struct {
	cc *grpc.ClientConn
}

func NewCampingServiceClient(cc *grpc.ClientConn) CampingServiceClient {
	return &campingServiceClient{cc}
}

func (c *campingServiceClient) GetAllSites(ctx context.Context, in *GetAllSitesRequest, opts ...grpc.CallOption) (*GetAllSitesResponse, error) {
	out := new(GetAllSitesResponse)
	err := c.cc.Invoke(ctx, "/camping.CampingService/GetAllSites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampingServiceServer is the server API for CampingService service.
type CampingServiceServer interface {
	GetAllSites(context.Context, *GetAllSitesRequest) (*GetAllSitesResponse, error)
}

func RegisterCampingServiceServer(s *grpc.Server, srv CampingServiceServer) {
	s.RegisterService(&_CampingService_serviceDesc, srv)
}

func _CampingService_GetAllSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampingServiceServer).GetAllSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/camping.CampingService/GetAllSites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampingServiceServer).GetAllSites(ctx, req.(*GetAllSitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CampingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "camping.CampingService",
	HandlerType: (*CampingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllSites",
			Handler:    _CampingService_GetAllSites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/api.proto",
}
