// Code generated by MockGen. DO NOT EDIT.
// Source: backend/db/db.go

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	db "github.com/znacol/camping/backend/db"
	proto "github.com/znacol/camping/backend/proto"
	reflect "reflect"
)

// MockAPI is a mock of API interface
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// GetSites mocks base method
func (m *MockAPI) GetSites(ctx context.Context) ([]*proto.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSites", ctx)
	ret0, _ := ret[0].([]*proto.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSites indicates an expected call of GetSites
func (mr *MockAPIMockRecorder) GetSites(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSites", reflect.TypeOf((*MockAPI)(nil).GetSites), ctx)
}

// GetNationalForest mocks base method
func (m *MockAPI) GetNationalForest(ctx context.Context, id int64) (db.NationalForest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNationalForest", ctx, id)
	ret0, _ := ret[0].(db.NationalForest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNationalForest indicates an expected call of GetNationalForest
func (mr *MockAPIMockRecorder) GetNationalForest(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNationalForest", reflect.TypeOf((*MockAPI)(nil).GetNationalForest), ctx, id)
}

// GetAllNationalForests mocks base method
func (m *MockAPI) GetAllNationalForests(ctx context.Context) ([]db.NationalForest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNationalForests", ctx)
	ret0, _ := ret[0].([]db.NationalForest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNationalForests indicates an expected call of GetAllNationalForests
func (mr *MockAPIMockRecorder) GetAllNationalForests(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNationalForests", reflect.TypeOf((*MockAPI)(nil).GetAllNationalForests), ctx)
}

// GetDistrict mocks base method
func (m *MockAPI) GetDistrict(ctx context.Context, id int64) (db.District, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistrict", ctx, id)
	ret0, _ := ret[0].(db.District)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistrict indicates an expected call of GetDistrict
func (mr *MockAPIMockRecorder) GetDistrict(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistrict", reflect.TypeOf((*MockAPI)(nil).GetDistrict), ctx, id)
}

// GetAllDistricts mocks base method
func (m *MockAPI) GetAllDistricts(ctx context.Context) ([]db.District, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDistricts", ctx)
	ret0, _ := ret[0].([]db.District)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDistricts indicates an expected call of GetAllDistricts
func (mr *MockAPIMockRecorder) GetAllDistricts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDistricts", reflect.TypeOf((*MockAPI)(nil).GetAllDistricts), ctx)
}

// CreateSite mocks base method
func (m *MockAPI) CreateSite(ctx context.Context, latitude, longitude float32, nationalForestID, districtID, altitude int64, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSite", ctx, latitude, longitude, nationalForestID, districtID, altitude, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSite indicates an expected call of CreateSite
func (mr *MockAPIMockRecorder) CreateSite(ctx, latitude, longitude, nationalForestID, districtID, altitude, notes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSite", reflect.TypeOf((*MockAPI)(nil).CreateSite), ctx, latitude, longitude, nationalForestID, districtID, altitude, notes)
}
